SELECT CONCAT(o.NAME, 
    CASE(o.OCCUPATION)
    WHEN 'Doctor' THEN '(D)'
    WHEN 'Professor' THEN '(P)'
    WHEN 'Singer' THEN '(S)'
    WHEN 'Actor' THEN '(A)'
    END)
FROM OCCUPATIONS o
ORDER BY o.NAME;

SELECT CONCAT('There are a total of ', COUNT(o.OCCUPATION), ' ', LOWER(o.OCCUPATION), 's.')
FROM OCCUPATIONS o
GROUP BY o.OCCUPATION
ORDER BY COUNT(o.OCCUPATION) ASC, o.OCCUPATION ASC;