DECLARE @a DECIMAL(10,4) = (select MIN(LAT_N) FROM STATION);
DECLARE @b DECIMAL(10,4) = (select MIN(LONG_W) FROM STATION);
DECLARE @c DECIMAL(10,4) = (select MAX(LAT_N) FROM STATION);
DECLARE @d DECIMAL(10,4) = (select MAX(LONG_W) FROM STATION);

SELECT ABS((@a-@c)) + ABS((@b-@d));