DECLARE @a DECIMAL(10,4) = (select MIN(LAT_N) FROM STATION);
DECLARE @b DECIMAL(10,4) = (select MIN(LONG_W) FROM STATION);
DECLARE @c DECIMAL(10,4) = (select MAX(LAT_N) FROM STATION);
DECLARE @d DECIMAL(10,4) = (select MAX(LONG_W) FROM STATION);

SELECT CAST(SQRT(POWER((@c-@a),2) + POWER((@d-@b),2)) as DECIMAL(10,4));